# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 750d4583beb26a3b30fce1bbf4bdc1c77fc3b1a394ddf928be6833375834d774007a66d61f011ca4df4244abf53b888a1d94a131942d195c359a0a0e02d632d5

test:
  secret_key_base: d45d66539a0acf4443c4eac459825d8e06f38193069b3c6bb6aa7b85d5169a31ec2d35852d6ce8a9d3a0de418676717a00fc68eedaebb9ff0b0f91f28d084f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
